# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miura/programming/research/DooR-API-Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miura/programming/research/DooR-API-Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miura/programming/research/DooR-API-Server/CMakeFiles /home/miura/programming/research/DooR-API-Server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miura/programming/research/DooR-API-Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DooR-API-Server

# Build rule for target.
DooR-API-Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DooR-API-Server
.PHONY : DooR-API-Server

# fast build rule for target.
DooR-API-Server/fast:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/build
.PHONY : DooR-API-Server/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/observer.o: src/observer.cpp.o

.PHONY : src/observer.o

# target to build an object file
src/observer.cpp.o:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/observer.cpp.o
.PHONY : src/observer.cpp.o

src/observer.i: src/observer.cpp.i

.PHONY : src/observer.i

# target to preprocess a source file
src/observer.cpp.i:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/observer.cpp.i
.PHONY : src/observer.cpp.i

src/observer.s: src/observer.cpp.s

.PHONY : src/observer.s

# target to generate assembly for a file
src/observer.cpp.s:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/observer.cpp.s
.PHONY : src/observer.cpp.s

src/server.o: src/server.cpp.o

.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/unix_socket.o: src/unix_socket.cpp.o

.PHONY : src/unix_socket.o

# target to build an object file
src/unix_socket.cpp.o:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/unix_socket.cpp.o
.PHONY : src/unix_socket.cpp.o

src/unix_socket.i: src/unix_socket.cpp.i

.PHONY : src/unix_socket.i

# target to preprocess a source file
src/unix_socket.cpp.i:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/unix_socket.cpp.i
.PHONY : src/unix_socket.cpp.i

src/unix_socket.s: src/unix_socket.cpp.s

.PHONY : src/unix_socket.s

# target to generate assembly for a file
src/unix_socket.cpp.s:
	$(MAKE) -f CMakeFiles/DooR-API-Server.dir/build.make CMakeFiles/DooR-API-Server.dir/src/unix_socket.cpp.s
.PHONY : src/unix_socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... DooR-API-Server"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/observer.o"
	@echo "... src/observer.i"
	@echo "... src/observer.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/unix_socket.o"
	@echo "... src/unix_socket.i"
	@echo "... src/unix_socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

